# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-Compare
version:      0.01
version_from: lib/Text/Compare.pm
installdirs:  site
requires:
    Carp:                          0
    HTML::Strip:                   0
    Lingua::Identify:              0
    Lingua::Stem:                  0
    Lingua::StopWords:             0
    Memoize:                       0
    Sparse::Vector:                0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
